# --8<-- [start:physical-interfaces]
/ interface ethernet-1/{1..2} #
admin-state enable
subinterface 1 {
ipv6 {
admin-state enable
router-advertisement {
router-role {
admin-state enable
}
}
}
}

/ network-instance default interface ethernet-1/{1..2}.1
# --8<-- [end:physical-interfaces]

# --8<-- [start:loopback-interfaces]
/ interface system0 {
subinterface 0 {
ipv4 {
admin-state enable
address 10.10.10.10/32
}
}
}

/ network-instance default interface system0.0
# --8<-- [end:loopback-interfaces]

# --8<-- [start:ebgp-underlay]
/ routing-policy {
prefix-set system-loopbacks {
prefix 10.0.0.0/8 mask-length-range 8..32 {
}
}
policy system-loopbacks-policy {
statement 1 {
match {
prefix-set system-loopbacks
}
action {
policy-result accept
}
}
}
}

/ network-instance default {
protocols {
bgp {
autonomous-system 4200000010
router-id 10.10.10.10
afi-safi ipv4-unicast {
admin-state enable
}
dynamic-neighbors {
interface ethernet-1/1.1 {
peer-group underlay
allowed-peer-as [
4200000001..4200000010
]
}
interface ethernet-1/2.1 {
peer-group underlay
allowed-peer-as [
4200000001..4200000010
]
}
}
group underlay {
export-policy system-loopbacks-policy
import-policy system-loopbacks-policy
}
}
}
ip-forwarding {
receive-ipv4-check false
}
}
# --8<-- [end:ebgp-underlay]

# --8<-- [start:ibgp-overlay]
/ network-instance default {
protocols {
bgp {
dynamic-neighbors {
accept {
match 0.0.0.0/0 {
peer-group overlay
}
}
}
group overlay {
peer-as 65535
afi-safi evpn {
admin-state enable
}
afi-safi ipv4-unicast {
admin-state disable
}
local-as {
as-number 65535
}
route-reflector {
client true
}
}
}
}
}
# --8<-- [end:ibgp-overlay]
